apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcoresample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspnetcoresample
  template:
    metadata:
      labels:
        app: aspnetcoresample
    spec:
      serviceAccountName: sa-migration
      initContainers:
        - name: aspnetcoresample-init
          image: groundnuty/k8s-wait-for:v2.0
          args:
            - "job"
            - "dummytoggle-job"
      containers:
      - name: aspnetcoresample
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcoresample-service
spec:
  selector:
    app: aspnetcoresample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort
